# 기본 제공 규칙에서 비활성화할 규칙들
disabled_rules:
    - colon                  # : 뒤에 공백 관련 규칙, 비활성화 결정이 필요
    - comma                  # , 뒤에 공백 관련 규칙, 비활성화 결정이 필요
    - control_statement      # if, while, for 등 괄호 관련 규칙
    - trailing_whitespace    # 코드 끝에 공백 방지 규칙, 비활성화에 주의
    - unneeded_override      # 필요없는 오버라이드 메서드 관련 규칙
    - todo                   # todo 작성 시 워닝 규칙
    - unused_closure_parameter # 클로저 파라미터 관련 규칙
    - multiple_closures_with_trailing_closure # 여러 클로저가 전달되는데 마지막 클로저만 트레일링 클로저 구문을 사용하는 경우 워닝 규칙
    - comment_spacing # 주석 뒤에 최소한 하나의 공백이 있어야 한다는 규칙

# 선택적으로 활성화할 규칙들 (기본 설정에 없으나 유용한 규칙들)
opt_in_rules:
    - empty_count               # .count == 0 대신 .isEmpty 권장하는 규칙
    - redundant_nil_coalescing  # 기본값으로 nil 설정된 경우 불필요한 ?? 사용 방지

# 규칙 설정 (각각의 규칙에 대해 경고와 에러 기준 설정)
force_cast: warning         # 강제 캐스팅 사용 시 경고
force_try:
    severity: warning       # 강제 try 사용 시 경고

# 한 줄의 최대 길이 제한
line_length:
    - 100
    
# 함수의 바디 길이 제한 (라인 수)
function_body_length:
    warning: 100
    
# 타입의 바디 길이 제한 (경고와 에러 기준)
type_body_length:
    - 300                   # 경고: 300줄
    - 400                   # 에러: 400줄

# 파일 길이 제한
file_length:
    warning: 350            # 350줄 이상이면 경고
    error: 600              # 600줄 이상이면 에러

# 타입 네이밍 규칙 (최소, 최대 길이 설정 및 예외 이름)
type_name:
    min_length: 4           # 경고: 최소 4자
    max_length:
        warning: 40         # 경고: 최대 40자
        error: 50           # 에러: 최대 50자

# 변수 및 상수 이름 규칙 (최소 길이 설정 및 예외 이름)
identifier_name:
    min_length: 2
    allowed_symbols: ["_"]  # 언더스코어(_) 허용
